### ISSUE TITLE
/displayset behavior is wonky and inconsistent

### ISSUE THREAD

**Issue by dan4222** [GCCempt/GCC_OpenSong_bot#105]

**Comment by AllDayJon** [comment]
@dan4222  can you provide any additional info on this?

**Comment by dan4222** [comment]
The set expansion that is supposed to occur when there is only one possible set to return doesn't happen.
Display Set command sometimes returns the wrong set when specifying a set name.

**Comment by Infosecguy10** [comment]
Resolved.
Changes:
modify mydiscord.py() - slash /display-set function to include set summary

Fixed the /display-set issue where only the most current set was being display.  The set name was being overwritten with a default setting

Issue;
Display set looks up set on the website
but to build the summary it looks locally so there could be a mismatch;
Changed process: if there the set is not found in the local sets directory, it is downloaded from the website in order to build the summaryh

**Comment by Infosecguy10** [comment]
Also, added set display after the set is built along with the set summary
