### ISSUE TITLE
Song validation does not carry through to when the set is built

### ISSUE THREAD

**Issue by dan4222** [GCCempt/GCC_OpenSong_bot#128]
In the case of putting lowercase song titles in the worship schedule, the initial song validation shows confirmation that the songs are valid however the song titles are not modified to actually match the song titles in the database resulting in the following:

![image](https://user-images.githubusercontent.com/34949488/120555383-fcf93c80-c3c8-11eb-8d0a-28c043622261.png)

![image](https://user-images.githubusercontent.com/34949488/120555425-0c788580-c3c9-11eb-9272-209bbf67942f.png)

**Comment by Infosecguy10** [comment]
Analysis:
Song validation issue:
As entered in the posted Worship Schedule: Marvelous Grace Of Our Loving Lord  (valid)
Worshipschedule.txt file:                                   Marvelous Grace of Our Loving Lord (as validated against the website)
Songs.txt file:                                                       Marvelous Grace Of Our Loving Lord
OpenSong Set:                                                    Marvelous Grace Of Our Loving Lord
Dropbox file:                                                       Marvelous Grace of Our Loving Lord
Website:                                                              Marvelous Grace of Our Loving Lord

**Comment by Infosecguy10** [comment]
Changes:

1.  filelist.py() - cleanup unused / unnecessary files which are no longer needed since we retain the original files now
2.  fixed syntax error in monitorfiles.py changed "fornat" to "format" - was causing an abort in the logs during /setcleanup
3.  delete songs.txt file as it is being written before the song validation for upper / lower case
4.  Remove songs.txt file from monitorfiles.cleanup()
5.  change readworshipschedule.readWS() to return a songs[] list of songs and presentation order
6.  change opensong.processongs() from read songs.txt to call readworshipschedule.readWS()
7.  change utils.parsemessages() -> remove call to readWS() lines 488 and lines 647
8.  Modify the startup_validation.run_test_scripts() to remove the readworshipschedul.readWS() call
9.  TBD - fix writehtml.readsongs() to call readworshipschedule.readWS() and process the songs array
10. Delete the songs.txt file
