### ISSUE TITLE
Build something that can test all functions of the discord bot in a standardized way

### ISSUE THREAD

**Issue by dan4222** [GCCempt/GCC_OpenSong_bot#16]

**Comment by dan4222** [comment]
The bot does not respond to its own messages otherwise it would go into a loop),  The "QA" script would have to issue commands as different "user".

**Comment by Infosecguy10** [comment]
Test scenarios to consider:
There 2 types of "messages" which the bot processes:
A. ANNOUNCEMENT POSTINGS
B. PROCESSING COMMANDS

A. ANNOUNCEMENT POSTINGS:
1. Announcement post for Sermon, Confession of Sin, Assurance of Pardon:

@here Dear all, here is Rev. Chuck Garriott's sermon info for this Sunday, 4/25:
Portrait of Humility (John 3:22–36)
 

@here here is the confession of sin to be put on screen, 4/25:
Gracious God, our sins are too heavy to carry, too real to hide, and too deep to undo.
Forgive what our lips tremble to name, what our hearts can no longer bear, and what has become for us a consuming fire of judgment. 
Set us free from a past that we cannot change; open to us a future in which we can be changed; and grant us grace to grow more and more in Your likeness and image; through Jesus Christ, the light of the world. Amen.

@here here is the assurance of pardon to be put on screen, 4/25:
Titus 3:4–7
4But when the goodness and loving kindness of God our Savior appeared, 5he saved us, not because of works done by us in righteousness, but according to his own mercy, by the washing of regeneration and renewal of the Holy Spirit, 6whom he poured out on us richly through Jesus Christ our Savior, 7so that being justified by his grace we might become heirs according to the hope of eternal life.

2. Worship Schedule
4/25/21 Worship Schedule 

Worship Leader: Pastor Arthur
Speaker: Rev. Chuck Garriott
Hymn: #76 Praise, My Soul, the King of Heaven - V1 V2 V3 V4 V5

Praise Team
Pastor Arthur, Judy

Booth
Computer: Mr. Rogers
Sound: Caleb
Camera: Daniel

Songs
* Shout to the Lord - V1 V2 C1 V1 V2 C1 C2 C3 E
* Hail to the King - V1 P C V2 P C C E
* Psalm 34 Taste and See - V1 V2 C V3 C C B B C C E
* Take My Life And Let It Be - Chris Tomlin - V1 V2 C V3 C C E

3. Bulletin Posting
@here The bulletin has been posted for 4/25

B. OPENSONG PROCESSING COMMANDS:
1. User Commands
$status
$addsong <song name> - add new song to Opensong database; include attachment
$displaysong <song name> - fuzzy matching
$displayset [optional <set name>] - defaults to set for the upcoming Sunday
$help

2. Administrative commands
$cleanup
$restore
$update
$rerun
$repost

**Comment by Infosecguy10** [comment]
I have an idea I want to try out for testing basic functionality outside of the Discord bot.

**Comment by Infosecguy10** [comment]
Built test_script.py to test end-to-end functionality outside of the Discord Bot.
Also added functionality to test a few commands: $displayset and $displaysong.
