### ISSUE TITLE
strip commas out of song order when processing the worship schedule

### ISSUE THREAD

**Issue by dan4222** [GCCempt/GCC_OpenSong_bot#35]

**Comment by Infosecguy10** [comment]
Last week worship schedule posting included the following:
Hymn: Jesus Shall Reign (To Our King Be Highest Praise) - V1, V2, C, V3, C, V4, C, C

When this is added to the song / set presentation order, OpenSong only displays the last choruse (C) since commas are nto valiid separator.
Request is to translate ',' separators within the song order into space

Testing:
Add invalid separators at worship schedule post.
verify that when the set gets built, the separators have beeen translated to spaces and that the song sequence displays correctly,

**Comment by Infosecguy10** [comment]
input stored in filelist.WorshipScheduleFilename
sample: Hymn: Jesus Shall Reign (To Our King Be Highest Praise) - V1, V2, C, V3, C, V4, C, C

Verified corrected output in 'songs.txt'
Jesus Shall Reign (To Our King Be Highest Praise) -  V1 V2 C V3 C V4 C C

**Comment by Infosecguy10** [comment]
Resolved.
